server:
  num_rounds: 40        
  min_fit_clients: 3
  min_eval_clients: 3         
  min_available_clients: 3
      
  

strategy:
  name: "FedAvg"                
  parameters:
    fraction_fit: 1.0          
    fraction_eval: 1.0          
