server:
  num_rounds: 20              
  min_fit_clients: 2     
  min_eval_clients: 2         
  min_available_clients: 2
      
  

strategy:
  name: "FedAvg"                
  parameters:
    fraction_fit: 1.0          
    fraction_eval: 1.0          
