server:
  num_rounds: 30              
  min_fit_clients: 5
  min_eval_clients: 5           
  min_available_clients: 5
      
  

strategy:
  name: "FedAvg"                
  parameters:
    fraction_fit: 1.0          
    fraction_eval: 1.0          
